# Recurrent
# 2020-11-02

all:
	@echo OK

train-debug:
	time /opt/Lens-linux/Bin/alens.sh scripts/train-debug.tcl

train-pmsp:
	time /opt/Lens-linux/Bin/alens.sh scripts/train-pmsp.tcl

train-jepg2017:
	echo time /opt/Lens-linux/Bin/alens.sh scripts/train-jepg2017.tcl

train-cogsci2020:
	time /opt/Lens-linux/Bin/alens.sh scripts/train-cogsci2020.tcl

experiment:
	time /opt/Lens-linux/Bin/alens.sh scripts/experiment.tcl

activations:
	time /opt/Lens-linux/Bin/alens.sh scripts/activations.tcl
