# Recurrent
# 2020-11-02

all:
	@echo OK

train-debug:
	time /opt/Lens-linux/Bin/alens.sh scripts/train-debug.tcl

train:
	time /opt/Lens-linux/Bin/alens.sh scripts/train-full.tcl

experiment:
	time /opt/Lens-linux/Bin/alens.sh scripts/experiment.tcl

activations:
	time /opt/Lens-linux/Bin/alens.sh scripts/activations.tcl
